
#define kAppName @"creativ365"

#define kJanuary @"January"
#define kFebruary @"February"
#define kMarch @"March"
#define kApril @"April"
#define kMay @"May"
#define kJune @"June"
#define kJuly @"July"
#define kAugust @"August"
#define kSeptember @"September"
#define kOctober @"October"
#define kNovember @"November"
#define kDecember @"December"